name: Build Docker images
description: Builds and pushes Docker images for the Test project 
inputs:
  tag:
    description: Docker tag
    required: true
    default: main
  isRelease:
    description: Is this a release build? If true, the latest tag will be applied
    required: false
    default: false
secrets:
  DOCKERHUB_USERNAME:
    description: Docker Hub username
    required: true
  DOCKERHUB_TOKEN:
    description: Docker Hub token
    required: true
runs:
    using: composite
    steps:
      - name: Test - Build and push Docker ${{ inputs.tag }} image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: vladikudrya/test-dockerhub:${{ inputs.tag }}
          push: true
      # - name: Test - Build and push Docker env image
      #   uses: docker/build-push-action@v4
      #   if: ${{ inputs.isRelease == 'true' }}
      #   with:
      #     context: .
      #     file: ./api/Dockerfile
      #     tags: vladikudrya/test-dockerhub:latest
      #     push: true
